# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/miket/Desktop/ADVEmbedded/keylogger/keyloggerProject/keyloggerProject.srcs/sources_1/bd/design_1/ip/design_1_my_keylogger_0_0/design_1_my_keylogger_0_0.xci
# IP: The module: 'design_1_my_keylogger_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/miket/Desktop/ADVEmbedded/keylogger/keyloggerProject/keyloggerProject.srcs/sources_1/bd/design_1/ip/design_1_my_keylogger_0_0/src/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/miket/Desktop/ADVEmbedded/keylogger/keyloggerProject/keyloggerProject.srcs/sources_1/bd/design_1/ip/design_1_my_keylogger_0_0/src/clk_wiz_0/clk_wiz_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/miket/Desktop/ADVEmbedded/keylogger/keyloggerProject/keyloggerProject.srcs/sources_1/bd/design_1/ip/design_1_my_keylogger_0_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc

# IP: C:/Users/miket/Desktop/ADVEmbedded/keylogger/keyloggerProject/keyloggerProject.srcs/sources_1/bd/design_1/ip/design_1_my_keylogger_0_0/design_1_my_keylogger_0_0.xci
# IP: The module: 'design_1_my_keylogger_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/miket/Desktop/ADVEmbedded/keylogger/keyloggerProject/keyloggerProject.srcs/sources_1/bd/design_1/ip/design_1_my_keylogger_0_0/src/clk_wiz_0/clk_wiz_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/miket/Desktop/ADVEmbedded/keylogger/keyloggerProject/keyloggerProject.srcs/sources_1/bd/design_1/ip/design_1_my_keylogger_0_0/src/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/miket/Desktop/ADVEmbedded/keylogger/keyloggerProject/keyloggerProject.srcs/sources_1/bd/design_1/ip/design_1_my_keylogger_0_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc
