# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Acer-PC/Documents/UNL/CSCE_436/lab/lab_3/lab_3.srcs/sources_1/bd/design_1/ip/design_1_my_oscope_ip_0_0/design_1_my_oscope_ip_0_0.xci
# IP: The module: 'design_1_my_oscope_ip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Acer-PC/Documents/UNL/CSCE_436/lab/lab_3/lab_3.srcs/sources_1/bd/design_1/ip/design_1_my_oscope_ip_0_0/src/clk_wiz_1_1/clk_wiz_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] -quiet

# IP: c:/Users/Acer-PC/Documents/UNL/CSCE_436/lab/lab_3/lab_3.srcs/sources_1/bd/design_1/ip/design_1_my_oscope_ip_0_0/src/clk_wiz_0_1/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/Acer-PC/Documents/UNL/CSCE_436/lab/lab_3/lab_3.srcs/sources_1/bd/design_1/ip/design_1_my_oscope_ip_0_0/src/clk_wiz_1_1/clk_wiz_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Acer-PC/Documents/UNL/CSCE_436/lab/lab_3/lab_3.srcs/sources_1/bd/design_1/ip/design_1_my_oscope_ip_0_0/src/clk_wiz_1_1/clk_wiz_1_ooc.xdc

# XDC: c:/Users/Acer-PC/Documents/UNL/CSCE_436/lab/lab_3/lab_3.srcs/sources_1/bd/design_1/ip/design_1_my_oscope_ip_0_0/src/clk_wiz_0_1/clk_wiz_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Acer-PC/Documents/UNL/CSCE_436/lab/lab_3/lab_3.srcs/sources_1/bd/design_1/ip/design_1_my_oscope_ip_0_0/src/clk_wiz_0_1/clk_wiz_0_ooc.xdc

# IP: C:/Users/Acer-PC/Documents/UNL/CSCE_436/lab/lab_3/lab_3.srcs/sources_1/bd/design_1/ip/design_1_my_oscope_ip_0_0/design_1_my_oscope_ip_0_0.xci
# IP: The module: 'design_1_my_oscope_ip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Acer-PC/Documents/UNL/CSCE_436/lab/lab_3/lab_3.srcs/sources_1/bd/design_1/ip/design_1_my_oscope_ip_0_0/src/clk_wiz_1_1/clk_wiz_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] -quiet

# IP: c:/Users/Acer-PC/Documents/UNL/CSCE_436/lab/lab_3/lab_3.srcs/sources_1/bd/design_1/ip/design_1_my_oscope_ip_0_0/src/clk_wiz_0_1/clk_wiz_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/Acer-PC/Documents/UNL/CSCE_436/lab/lab_3/lab_3.srcs/sources_1/bd/design_1/ip/design_1_my_oscope_ip_0_0/src/clk_wiz_1_1/clk_wiz_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Acer-PC/Documents/UNL/CSCE_436/lab/lab_3/lab_3.srcs/sources_1/bd/design_1/ip/design_1_my_oscope_ip_0_0/src/clk_wiz_1_1/clk_wiz_1_ooc.xdc

# XDC: c:/Users/Acer-PC/Documents/UNL/CSCE_436/lab/lab_3/lab_3.srcs/sources_1/bd/design_1/ip/design_1_my_oscope_ip_0_0/src/clk_wiz_0_1/clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Acer-PC/Documents/UNL/CSCE_436/lab/lab_3/lab_3.srcs/sources_1/bd/design_1/ip/design_1_my_oscope_ip_0_0/src/clk_wiz_0_1/clk_wiz_0_ooc.xdc
